export const options = [
    { value: 'FLOOR_1', label: 'Primera planta' },
    { value: 'FLOOR_2', label: 'Segunda planta' },
    { value: 'FLOOR_3UP', label: 'Tercera planta (o superior)' },
    { value: 'HOUSE_ROOM', label: 'Habitación de casa' },
    { value: 'FLAT_ROOM', label: 'Habitación de piso' },
    { value: 'BASEMENT', label: 'Sótano' },
    { value: 'GARAGE', label: 'Garaje' },
    { value: 'STORAGE_ROOM', label: 'Trastero' },
    { value: 'INDUSTRIAL_WAREHOUSE', label: 'Nave industrial' },
    { value: 'OFFICE_ROOM', label: 'Oficina' },
    { value: 'PENTHOUSE', label: 'Ático' },
    { value: 'ELEVATOR', label: 'Ascensor' },
    { value: 'WET', label: 'Con humedad' },
    { value: 'DRY', label: 'Sin humedad' },
    { value: 'COLD', label: 'Frío' },
    { value: 'WARM', label: 'Cálido' },
    { value: 'HOT', label: 'Caluroso' },
    { value: 'SECURITY_ALARM', label: 'Con alarma de seguridad' },
    { value: 'VIDEO_MONITORING', label: 'Con cámara de seguridad' },
    { value: 'FIRE_ALARM', label: 'Con alamra de incendios' },
    { value: 'GROUND_FLOOR', label: 'Planta baja' },
    { value: 'SOCKET', label: 'Con enchufes' },
    { value: 'INDOOR', label: 'Interiores' },
    { value: 'OUTDOOR', label: 'Al aire libre' },
    { value: 'NARROW_ACCESS', label: 'Acceso estrecho' },
    { value: 'MEDIUM_WIDTH_ACCESS', label: 'Acceso de ancho medio' },
    { value: 'WIDE_ACCESS', label: 'Acceso amplio' },
]
